package com.cj.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cjenglish.db.WordItem;
import com.cjenglish.db.WordTitle;

import com.cj.db.greendao.WordItemDao;
import com.cj.db.greendao.WordTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordItemDaoConfig;
    private final DaoConfig wordTitleDaoConfig;

    private final WordItemDao wordItemDao;
    private final WordTitleDao wordTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordItemDaoConfig = daoConfigMap.get(WordItemDao.class).clone();
        wordItemDaoConfig.initIdentityScope(type);

        wordTitleDaoConfig = daoConfigMap.get(WordTitleDao.class).clone();
        wordTitleDaoConfig.initIdentityScope(type);

        wordItemDao = new WordItemDao(wordItemDaoConfig, this);
        wordTitleDao = new WordTitleDao(wordTitleDaoConfig, this);

        registerDao(WordItem.class, wordItemDao);
        registerDao(WordTitle.class, wordTitleDao);
    }
    
    public void clear() {
        wordItemDaoConfig.getIdentityScope().clear();
        wordTitleDaoConfig.getIdentityScope().clear();
    }

    public WordItemDao getWordItemDao() {
        return wordItemDao;
    }

    public WordTitleDao getWordTitleDao() {
        return wordTitleDao;
    }

}
